autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

image:
  repository: ghcr.io/htdangkhoa-platform/authenticator-svc
  tag: 25da101b293a572d3ed2dd07f29a8c2bdaa9e02d
  pullSecrets: docker-registry

service:
  port: 80

  livenessProbe:
    enabled: true
    path: /liveness
    initialDelaySeconds: 30
    periodSeconds: 10

  readinessProbe:
    enabled: true
    path: /readiness
    initialDelaySeconds: 30
    periodSeconds: 10

imagePullSecrets: []

extraContainers:
  - name: authenticator-svc2
    image: ghcr.io/htdangkhoa-platform/authenticator-svc:25da101b293a572d3ed2dd07f29a8c2bdaa9e02d
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: authenticator-svc-configmap
      - secretRef:
          name: authenticator-svc-secret

extraPorts:
  - protocol: TCP
    port: 8080
    targetPort: http

ingress:
  enabled: true
  className: nginx
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: svc.authenticator.htdangkhoa.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: authenticator-svc-service-tls
      hosts:
        - svc.authenticator.htdangkhoa.com