apiVersion: v1
kind: Service
metadata:
  name: {{ include "htdangkhoa-platform.fullname" . }}
  labels:
    {{- include "htdangkhoa-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "htdangkhoa-platform.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}

    {{- if .Values.service.extraPorts }}
    {{- range .Values.service.extraPorts }}
    - protocol: {{ .protocol }}
      port: {{ .containerPort }}
      targetPort: {{ .targetPort | default "http" }}
    {{- end }}
    {{- end }}

    {{- if .Values.extraContainers }}
    {{- range .Values.extraContainers }}
    - protocol: TCP
      port: {{ .containerPort }}
      targetPort: {{ .targetPort | default "http" }}
    {{- end }}
    {{- end }}