apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  labels:
    app: "{{ .Release.Name }}"
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: "{{ .Release.Name }}"
    version: "{{ .Chart.Version }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}

    {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4 }}
    {{- end }}