name: Release Charts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Create Release
        run: |
          helm package charts/* --destination .cr-release

      - name: Push Release
        uses: softprops/action-gh-release@v1
        with:
          files: charts/*.tgz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Index
        run: |
          for file in .cr-release/*.tgz; do
            helm repo index --merge index.yaml --url https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/ .cr-release
          done