name: Release Charts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Create Release
        run: |
          helm package charts/* --destination .cr-release

      - name: Update Index
        run: |
          helm repo index --url https://github.com/${{ github.repository }}/releases/download/${{ github.ref }} ./.cr-release
          mv .cr-release/index.yaml index.yaml

      - name: Commit and Push
        run: |
          git add index.yaml
          git commit -m "Release ${{ github.ref }}"
          git tag -a ${{ github.ref }} -m "Release ${{ github.ref }}"
          git push origin ${{ github.ref }}:${{ github.ref }}
          git push origin --tags

      - name: Push Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .cr-release/*
          token: ${{ secrets.GITHUB_TOKEN }}